### PR TITLE
fix: shared album and openapi patch album

### LINKED ISSUE #123: Fix album sharing
Correct album path to add sharing

### PR DESCRIPTION
**Pull request by BaptistePgn**
closes #123

### CODE REVIEW

**Review by AndreasLrx — APPROVED** [review]

File: back/src/api/albums.rs [hunk 1]
```diff
@@ -350,9 +351,40 @@ pub async fn edit_album(
...
+                    .filter(users::email.eq_any(patch.shared_with.as_ref().unwrap()))
+                    .load::<Uuid>(conn)
+                    .map_err(DatabaseError::<ApiError>::from)?;
+
+                diesel::delete(shared_albums::table.filter(shared_albums::album_id.eq(*album_id)))
+                    .execute(conn)
+                    .map_err(DatabaseError::<ApiError>::from)?;
+
+                // Insert the new shared users
+                insert_into(shared_albums::table)
```
Comment (MisterPeModder) [inline back/src/api/albums.rs:366]: Be consistent, either use `diesel::delete(), diesel::update(), ...` everywhere ***OR*** use imported functions `delete(), update()`

**Review by MisterPeModder — CHANGES_REQUESTED** [review]

**Review by MisterPeModder — APPROVED** [review]
